name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:latest
    steps:
      - uses: actions/checkout@v2
      - run: perl -V
      - run: cpanm --installdeps .
      - run: perl Makefile.PL && make && make test
      
